// src/lib/react/GlobeComponent.tsx

import React, { useRef, useEffect, useState } from 'react';
import { ThreeGlobeCore, GlobeOptions } from '../geospatial-core';
import type { GeoLocation, GlobeEventHandlers } from '../geospatial-core/types';

interface GlobeComponentProps {
  options?: Partial<GlobeOptions>;
  selectedLocation?: GeoLocation;
  onReady?: (api: any) => void;
  onFlyComplete?: () => void;
  onError?: (error: Error) => void;
}

/**
 * React component wrapper for ThreeGlobeCore
 */
export const GlobeComponent: React.FC<GlobeComponentProps> = ({
  options,
  selectedLocation,
  onReady,
  onFlyComplete,
  onError
}) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const globeRef = useRef<ThreeGlobeCore | null>(null);
  const [isReady, setIsReady] = useState(false);
  
  // Initialize globe when component mounts
  useEffect(() => {
    if (!containerRef.current) return;
    
    const globe = new ThreeGlobeCore(options);
    globeRef.current = globe;
    
    const eventHandlers: GlobeEventHandlers = {
      onReady: (api) => {
        setIsReady(true);
        if (onReady) onReady(api);
      },
      onFlyComplete,
      onError
    };
    
    globe.init({
      getElement: () => containerRef.current,
      getDimensions: () => ({
        width: containerRef.current?.clientWidth || 300,
        height: containerRef.current?.clientHeight || 300
      }),
      onResize: (callback) => {
        const handleResize = () => {
          if (containerRef.current) callback();
        };
        window.addEventListener('resize', handleResize);
        return () => window.removeEventListener('resize', handleResize);
      },
      onCleanup: (callback) => {}
    }, eventHandlers);
    
    return () => {
      if (globeRef.current) {
        globeRef.current.dispose();
        globeRef.current = null;
      }
    };
  }, []); // Empty dependency array means initialize once
  
  // Handle location changes
  useEffect(() => {
    if (globeRef.current && isReady && selectedLocation) {
      globeRef.current.setLocation(selectedLocation);
    }
  }, [selectedLocation, isReady]);
  
  return (
    <div 
      ref={containerRef} 
      className="w-full h-full" 
      style={{ 
        position: 'relative',
        overflow: 'hidden',
        backgroundColor: 'black'
      }}
    >
      {!isReady && (
        <div className="absolute inset-0 flex items-center justify-center bg-black text-white">
          <div className="text-center">
            <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-blue-500 mx-auto mb-4"></div>
            <h3 className="text-xl font-bold">Loading Globe</h3>
          </div>
        </div>
      )}
    </div>
  );
};

// src/lib/angular/globe.component.ts

/**
 * Example Angular component for the globe
 * This would be in a separate Angular project with its own build system
 */

/* 
// This is how the Angular component would look:

import { Component, ElementRef, ViewChild, Input, Output, EventEmitter, OnInit, OnDestroy } from '@angular/core';
import { ThreeGlobeCore } from '../geospatial-core';
import { GlobeOptions, GeoLocation } from '../geospatial-core/types';

@Component({
  selector: 'app-globe',
  template: `
    <div #container 
         class="globe-container"
         [ngStyle]="{
           'width': '100%',
           'height': '100%',
           'position': 'relative',
           'background-color': 'black'
         }">
      <div *ngIf="!isReady" 
           class="loading-overlay"
           style="position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; background-color: rgba(0,0,0,0.8);">
        <div class="loading-content" style="text-align: center; color: white;">
          <div class="spinner"></div>
          <h3>Loading Globe</h3>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .globe-container {
      overflow: hidden;
    }
    
    .spinner {
      border: 4px solid rgba(255,255,255,0.3);
      border-radius: 50%;
      border-top: 4px solid #3498db;
      width: 40px;
      height: 40px;
      animation: spin 1s linear infinite;
      margin: 0 auto 15px;
    }
    
    @keyframes spin {
      0% { transform: rotate(0deg); }
      100% { transform: rotate(360deg); }
    }
  `]
})
export class GlobeComponent implements OnInit, OnDestroy {
  @ViewChild('container', { static: true }) containerRef: ElementRef;
  
  @Input() options: Partial<GlobeOptions> = {};
  @Input() selectedLocation: GeoLocation | null = null;
  
  @Output() ready = new EventEmitter<any>();
  @Output() flyComplete = new EventEmitter<void>();
  @Output() error = new EventEmitter<Error>();
  
  private globe: ThreeGlobeCore | null = null;
  isReady = false;
  
  ngOnInit() {
    this.initGlobe();
  }
  
  ngOnDestroy() {
    if (this.globe) {
      this.globe.dispose();
      this.globe = null;
    }
  }
  
  private initGlobe() {
    try {
      this.globe = new ThreeGlobeCore(this.options);
      
      this.globe.init({
        getElement: () => this.containerRef.nativeElement,
        getDimensions: () => ({
          width: this.containerRef.nativeElement.clientWidth,
          height: this.containerRef.nativeElement.clientHeight
        }),
        onResize: (callback) => {
          const resizeObserver = new ResizeObserver(() => callback());
          resizeObserver.observe(this.containerRef.nativeElement);
          return () => resizeObserver.disconnect();
        },
        onCleanup: (callback) => {}
      }, {
        onReady: (api) => {
          this.isReady = true;
          this.ready.emit(api);
        },
        onFlyComplete: () => {
          this.flyComplete.emit();
        },
        onError: (error) => {
          this.error.emit(error);
        }
      });
      
    } catch (error) {
      console.error('Failed to initialize globe:', error);
      this.error.emit(error as Error);
    }
  }
  
  ngOnChanges() {
    if (this.globe && this.isReady && this.selectedLocation) {
      this.globe.setLocation(this.selectedLocation);
    }
  }
}
*/

// This file would need to be in an Angular library project
// Here we're just providing a placeholder file
export const ANGULAR_COMPONENT_PLACEHOLDER = `
// GlobeComponent implementation for Angular would go here
// See commented code above for reference implementation
`;
